// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR3hTHQwk2nt63sLikxRipQmMNlumMy8E',
    appId: '1:634985475298:web:9f8080c477de87de2542bb',
    messagingSenderId: '634985475298',
    projectId: 'feira-de-troca',
    authDomain: 'feira-de-troca.firebaseapp.com',
    storageBucket: 'feira-de-troca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMI5SjILLMVvOu0nouwnbIy74fKnoi0E',
    appId: '1:634985475298:android:a94978fbb25d3f792542bb',
    messagingSenderId: '634985475298',
    projectId: 'feira-de-troca',
    storageBucket: 'feira-de-troca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWnWxr2i9M84S_ptbFGOeznhXVO8yhQg',
    appId: '1:634985475298:ios:ac887bd7ac232c482542bb',
    messagingSenderId: '634985475298',
    projectId: 'feira-de-troca',
    storageBucket: 'feira-de-troca.firebasestorage.app',
    iosBundleId: 'com.example.feiraDeTrocaCotemig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWnWxr2i9M84S_ptbFGOeznhXVO8yhQg',
    appId: '1:634985475298:ios:ac887bd7ac232c482542bb',
    messagingSenderId: '634985475298',
    projectId: 'feira-de-troca',
    storageBucket: 'feira-de-troca.firebasestorage.app',
    iosBundleId: 'com.example.feiraDeTrocaCotemig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR3hTHQwk2nt63sLikxRipQmMNlumMy8E',
    appId: '1:634985475298:web:ebfec72c984c90552542bb',
    messagingSenderId: '634985475298',
    projectId: 'feira-de-troca',
    authDomain: 'feira-de-troca.firebaseapp.com',
    storageBucket: 'feira-de-troca.firebasestorage.app',
  );
}
